
-- Create translations table
CREATE TABLE public.translations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key VARCHAR NOT NULL,
  language_code VARCHAR REFERENCES public.languages(code) NOT NULL,
  value TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(key, language_code)
);

-- Enable RLS
ALTER TABLE public.translations ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Anyone can read translations" ON public.translations
  FOR SELECT TO public USING (true);

-- Insert Arabic translations
INSERT INTO public.translations (key, language_code, value) VALUES
('heroTitle', 'ar', 'نحن هنا لدعمك'),
('heroSubtitle', 'ar', 'احصل على المساعدة التي تحتاجها بسرعة وسهولة. فريق الدعم الفني لدينا متواجد على مدار الساعة.'),
('startChat', 'ar', 'ابدأ الدردشة الآن'),
('learnMore', 'ar', 'اعرف المزيد'),
('home', 'ar', 'الرئيسية'),
('chat', 'ar', 'دردشة'),
('faq', 'ar', 'الأسئلة الشائعة'),
('register', 'ar', 'تسجيل'),
('login', 'ar', 'تسجيل الدخول'),
('logout', 'ar', 'تسجيل الخروج'),
('email', 'ar', 'البريد الإلكتروني'),
('password', 'ar', 'كلمة المرور'),
('enterEmail', 'ar', 'أدخل بريدك الإلكتروني'),
('enterPassword', 'ar', 'أدخل كلمة مرورك'),
('loginSuccess', 'ar', 'تم تسجيل الدخول بنجاح!'),
('loginError', 'ar', 'فشل تسجيل الدخول. يرجى التحقق من بيانات الاعتماد الخاصة بك.'),
('noAccount', 'ar', 'ليس لديك حساب؟'),
('welcomeBack', 'ar', 'مرحباً بعودتك!'),
('loading', 'ar', 'جار التحميل...'),
('typeMessage', 'ar', 'اكتب رسالتك هنا...'),
('technicalSupport', 'ar', 'الدعم الفني'),
('onlineNow', 'ar', 'متصل الآن'),
('transferToHuman', 'ar', 'التحويل إلى موظف بشري'),
('transferringToHuman', 'ar', 'جاري التحويل إلى موظف بشري...'),
('menu', 'ar', 'القائمة'),
('previousChats', 'ar', 'المحادثات السابقة'),
('settings', 'ar', 'الإعدادات'),
('languageSettings', 'ar', 'إعدادات اللغة'),
('languageSettingsDesc', 'ar', 'اختر لغة التطبيق المفضلة لديك'),
('currentLanguage', 'ar', 'اللغة الحالية'),
('appearance', 'ar', 'المظهر'),
('appearanceDesc', 'ar', 'تخصيص مظهر التطبيق'),
('theme', 'ar', 'السمة'),
('themeDesc', 'ar', 'اختر بين الوضع الفاتح والداكن'),
('light', 'ar', 'فاتح'),
('dark', 'ar', 'داكن'),
('notifications', 'ar', 'الإشعارات'),
('notificationsDesc', 'ar', 'إدارة تفضيلات الإشعارات'),
('emailNotifications', 'ar', 'إشعارات البريد الإلكتروني'),
('emailNotificationsDesc', 'ar', 'تلقي إشعارات عبر البريد الإلكتروني'),
('pushNotifications', 'ar', 'الإشعارات الفورية'),
('pushNotificationsDesc', 'ar', 'تلقي إشعارات فورية في المتصفح'),
('enabled', 'ar', 'مفعل'),
('disabled', 'ar', 'معطل'),
('account', 'ar', 'الحساب'),
('accountDesc', 'ar', 'إدارة معلومات حسابك'),
('editProfile', 'ar', 'تعديل الملف الشخصي'),
('changePassword', 'ar', 'تغيير كلمة المرور'),
('saveSettings', 'ar', 'حفظ الإعدادات'),
('settingsSaved', 'ar', 'تم حفظ الإعدادات بنجاح'),
('settingsDesc', 'ar', 'قم بتخصيص تجربتك وإدارة حسابك'),
('actions', 'ar', 'الإجراءات'),
('adminDashboard', 'ar', 'لوحة تحكم المشرف'),
('manageSystemSettings', 'ar', 'إدارة إعدادات النظام والمحتوى'),
('featuresTitle', 'ar', 'المميزات'),
('feature1Title', 'ar', 'دعم فوري على مدار الساعة'),
('feature1Desc', 'ar', 'احصل على إجابات فورية لاستفساراتك في أي وقت من اليوم'),
('feature2Title', 'ar', 'ذكاء اصطناعي متقدم'),
('feature2Desc', 'ar', 'تقنيات حديثة تفهم احتياجاتك وتقدم حلول دقيقة'),
('feature3Title', 'ar', 'دعم متعدد اللغات'),
('feature3Desc', 'ar', 'تحدث معنا بالعربية أو الإنجليزية كما تفضل'),
('statsTitle', 'ar', 'إحصائياتنا'),
('stat1', 'ar', 'مستخدم راضٍ'),
('stat2', 'ar', 'مشكلة تم حلها'),
('stat3', 'ar', 'متوسط وقت الاستجابة'),
('stat4', 'ar', 'معدل الرضا'),
('users', 'ar', 'المستخدمون'),
('chats', 'ar', 'المحادثات'),
('faqs', 'ar', 'الأسئلة الشائعة'),
('usersManagement', 'ar', 'إدارة المستخدمين'),
('manageRegisteredUsers', 'ar', 'إدارة المستخدمين المسجلين في النظام'),
('name', 'ar', 'الاسم'),
('joinDate', 'ar', 'تاريخ الانضمام'),
('status', 'ar', 'الحالة'),
('active', 'ar', 'نشط'),
('inactive', 'ar', 'غير نشط'),
('chatsManagement', 'ar', 'إدارة المحادثات'),
('viewAllChats', 'ar', 'عرض جميع المحادثات التي تمت مع البوت'),
('user', 'ar', 'المستخدم'),
('startTime', 'ar', 'وقت البداية'),
('endTime', 'ar', 'وقت النهاية'),
('duration', 'ar', 'المدة'),
('completed', 'ar', 'مكتملة'),
('ongoing', 'ar', 'جارية'),
('faqsManagement', 'ar', 'إدارة الأسئلة الشائعة'),
('manageFAQDatabase', 'ar', 'إدارة قاعدة بيانات الأسئلة الشائعة'),
('addQuestion', 'ar', 'إضافة سؤال'),
('addNewQuestion', 'ar', 'إضافة سؤال جديد'),
('fillQuestionInBothLanguages', 'ar', 'املأ السؤال والإجابة باللغتين'),
('questionArabic', 'ar', 'السؤال (عربي)'),
('answerArabic', 'ar', 'الإجابة (عربي)'),
('questionEnglish', 'ar', 'السؤال (إنجليزي)'),
('answerEnglish', 'ar', 'الإجابة (إنجليزي)'),
('enterQuestionArabic', 'ar', 'أدخل السؤال باللغة العربية'),
('enterAnswerArabic', 'ar', 'أدخل الإجابة باللغة العربية'),
('enterQuestionEnglish', 'ar', 'Enter question in English'),
('enterAnswerEnglish', 'ar', 'Enter answer in English'),
('cancel', 'ar', 'إلغاء'),
('save', 'ar', 'حفظ'),
('fillAllFields', 'ar', 'يرجى ملء جميع الحقول'),
('faqAdded', 'ar', 'تم إضافة السؤال بنجاح'),
('faqDeleted', 'ar', 'تم حذف السؤال بنجاح');

-- Insert English translations
INSERT INTO public.translations (key, language_code, value) VALUES
('heroTitle', 'en', 'We are here to support you'),
('heroSubtitle', 'en', 'Get the help you need quickly and easily. Our technical support team is available 24/7.'),
('startChat', 'en', 'Start Chat Now'),
('learnMore', 'en', 'Learn More'),
('home', 'en', 'Home'),
('chat', 'en', 'Chat'),
('faq', 'en', 'FAQ'),
('register', 'en', 'Register'),
('login', 'en', 'Login'),
('logout', 'en', 'Logout'),
('email', 'en', 'Email'),
('password', 'en', 'Password'),
('enterEmail', 'en', 'Enter your email'),
('enterPassword', 'en', 'Enter your password'),
('loginSuccess', 'en', 'Logged in successfully!'),
('loginError', 'en', 'Login failed. Please check your credentials.'),
('noAccount', 'en', 'Don''t have an account?'),
('welcomeBack', 'en', 'Welcome back!'),
('loading', 'en', 'Loading...'),
('typeMessage', 'en', 'Type your message here...'),
('technicalSupport', 'en', 'Technical Support'),
('onlineNow', 'en', 'Online Now'),
('transferToHuman', 'en', 'Transfer to Human'),
('transferringToHuman', 'en', 'Transferring to human...'),
('menu', 'en', 'Menu'),
('previousChats', 'en', 'Previous Chats'),
('settings', 'en', 'Settings'),
('languageSettings', 'en', 'Language Settings'),
('languageSettingsDesc', 'en', 'Choose your preferred application language'),
('currentLanguage', 'en', 'Current Language'),
('appearance', 'en', 'Appearance'),
('appearanceDesc', 'en', 'Customize the application appearance'),
('theme', 'en', 'Theme'),
('themeDesc', 'en', 'Choose between light and dark mode'),
('light', 'en', 'Light'),
('dark', 'en', 'Dark'),
('notifications', 'en', 'Notifications'),
('notificationsDesc', 'en', 'Manage your notification preferences'),
('emailNotifications', 'en', 'Email Notifications'),
('emailNotificationsDesc', 'en', 'Receive notifications via email'),
('pushNotifications', 'en', 'Push Notifications'),
('pushNotificationsDesc', 'en', 'Receive instant browser notifications'),
('enabled', 'en', 'Enabled'),
('disabled', 'en', 'Disabled'),
('account', 'en', 'Account'),
('accountDesc', 'en', 'Manage your account information'),
('editProfile', 'en', 'Edit Profile'),
('changePassword', 'en', 'Change Password'),
('saveSettings', 'en', 'Save Settings'),
('settingsSaved', 'en', 'Settings saved successfully'),
('settingsDesc', 'en', 'Customize your experience and manage your account'),
('actions', 'en', 'Actions'),
('adminDashboard', 'en', 'Admin Dashboard'),
('manageSystemSettings', 'en', 'Manage system settings and content'),
('featuresTitle', 'en', 'Features'),
('feature1Title', 'en', '24/7 Instant Support'),
('feature1Desc', 'en', 'Get instant answers to your questions at any time of the day'),
('feature2Title', 'en', 'Advanced AI Technology'),
('feature2Desc', 'en', 'Modern technology that understands your needs and provides accurate solutions'),
('feature3Title', 'en', 'Multi-language Support'),
('feature3Desc', 'en', 'Talk to us in Arabic or English as you prefer'),
('statsTitle', 'en', 'Our Statistics'),
('stat1', 'en', 'Happy Users'),
('stat2', 'en', 'Problems Solved'),
('stat3', 'en', 'Average Response Time'),
('stat4', 'en', 'Satisfaction Rate'),
('users', 'en', 'Users'),
('chats', 'en', 'Chats'),
('faqs', 'en', 'FAQs'),
('usersManagement', 'en', 'Users Management'),
('manageRegisteredUsers', 'en', 'Manage registered users in the system'),
('name', 'en', 'Name'),
('joinDate', 'en', 'Join Date'),
('status', 'en', 'Status'),
('active', 'en', 'Active'),
('inactive', 'en', 'Inactive'),
('chatsManagement', 'en', 'Chats Management'),
('viewAllChats', 'en', 'View all chats that were conducted with the bot'),
('user', 'en', 'User'),
('startTime', 'en', 'Start Time'),
('endTime', 'en', 'End Time'),
('duration', 'en', 'Duration'),
('completed', 'en', 'Completed'),
('ongoing', 'en', 'Ongoing'),
('faqsManagement', 'en', 'FAQs Management'),
('manageFAQDatabase', 'en', 'Manage FAQ database'),
('addQuestion', 'en', 'Add Question'),
('addNewQuestion', 'en', 'Add New Question'),
('fillQuestionInBothLanguages', 'en', 'Fill the question and answer in both languages'),
('questionArabic', 'en', 'Question (Arabic)'),
('answerArabic', 'en', 'Answer (Arabic)'),
('questionEnglish', 'en', 'Question (English)'),
('answerEnglish', 'en', 'Answer (English)'),
('enterQuestionArabic', 'en', 'أدخل السؤال باللغة العربية'),
('enterAnswerArabic', 'en', 'أدخل الإجابة باللغة العربية'),
('enterQuestionEnglish', 'en', 'Enter question in English'),
('enterAnswerEnglish', 'en', 'Enter answer in English'),
('cancel', 'en', 'Cancel'),
('save', 'en', 'Save'),
('fillAllFields', 'en', 'Please fill all fields'),
('faqAdded', 'en', 'FAQ added successfully'),
('faqDeleted', 'en', 'FAQ deleted successfully');
