// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddmdrangzsozvuipexdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkbWRyYW5nenNvenZ1aXBleGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTk1NTksImV4cCI6MjA2NTY3NTU1OX0.MAkamsuBKliEmXrXEXhLWEvv-P3PA3zS2Rdi32SdtKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);